### PR TITLE
Bump yodeploy version used for deploy

### PR DESCRIPTION
**Pull request by zoidbergwill**
Deploy is broken because of dangling symlinks

### CODE REVIEW

**Comment by zoidbergwill** [comment]
#Lucid

```
$ dpkg -L python-gtk2
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-gtk2
/usr/share/doc/python-gtk2/MAPPING.gz
/usr/share/doc/python-gtk2/TODO
/usr/share/doc/python-gtk2/changelog.Debian.gz
/usr/share/doc/python-gtk2/README.Debian
/usr/share/doc/python-gtk2/copyright
/usr/share/doc/python-gtk2/changelog.gz
/usr/share/doc/python-gtk2/NEWS.gz
/usr/share/doc/python-gtk2/README.gz
/usr/share/doc/python-gtk2/THREADS.gz
/usr/share/pyshared
/usr/share/pyshared/gtk-2.0
/usr/share/pyshared/gtk-2.0/gtk
/usr/share/pyshared/gtk-2.0/gtk/deprecation.py
/usr/share/pyshared/gtk-2.0/gtk/_lazyutils.py
/usr/share/pyshared/gtk-2.0/gtk/__init__.py
/usr/share/pyshared/gtk-2.0/gtk/compat.py
/usr/share/pyshared/gtk-2.0/gtk/keysyms.py
/usr/share/python-support
/usr/share/python-support/python-gtk2.public
/usr/lib
/usr/lib/pyshared
/usr/lib/pyshared/python2.6
/usr/lib/pyshared/python2.6/gtk-2.0
/usr/lib/pyshared/python2.6/gtk-2.0/gtk
/usr/lib/pyshared/python2.6/gtk-2.0/gtk/_gtk.so
/usr/lib/pyshared/python2.6/gtk-2.0/gtkunixprint.so
/usr/lib/pyshared/python2.6/gtk-2.0/atk.so
/usr/lib/pyshared/python2.6/gtk-2.0/pango.so
/usr/lib/pyshared/python2.6/gtk-2.0/pangocairo.so
```

#Precise
```
$ dpkg -L python-gtk2
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-gtk2
/usr/share/doc/python-gtk2/NEWS.gz
/usr/share/doc/python-gtk2/THREADS.gz
/usr/share/doc/python-gtk2/copyright
/usr/share/doc/python-gtk2/README
/usr/share/doc/python-gtk2/TODO
/usr/share/doc/python-gtk2/changelog.Debian.gz
/usr/share/doc/python-gtk2/README.Debian
/usr/share/doc/python-gtk2/MAPPING.gz
/usr/share/pyshared
/usr/share/pyshared/gtk-2.0
/usr/share/pyshared/gtk-2.0/gtk
/usr/share/pyshared/gtk-2.0/gtk/_lazyutils.py
/usr/share/pyshared/gtk-2.0/gtk/compat.py
/usr/share/pyshared/gtk-2.0/gtk/deprecation.py
/usr/share/pyshared/gtk-2.0/gtk/__init__.py
/usr/share/pyshared/gtk-2.0/gtk/keysyms.py
/usr/lib
/usr/lib/pyshared
/usr/lib/pyshared/python2.7
/usr/lib/pyshared/python2.7/gtk-2.0
/usr/lib/pyshared/python2.7/gtk-2.0/gtk
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/gtk-2.0/pangocairo.so
/usr/lib/python2.7/dist-packages/gtk-2.0/gtkunixprint.so
/usr/lib/python2.7/dist-packages/gtk-2.0/atk.so
/usr/lib/python2.7/dist-packages/gtk-2.0/pango.so
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_gtk.so
/usr/lib/pyshared/python2.7/gtk-2.0/pangocairo.so
/usr/lib/pyshared/python2.7/gtk-2.0/gtkunixprint.so
/usr/lib/pyshared/python2.7/gtk-2.0/atk.so
/usr/lib/pyshared/python2.7/gtk-2.0/pango.so
/usr/lib/pyshared/python2.7/gtk-2.0/gtk/_gtk.so
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_lazyutils.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/compat.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/deprecation.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/keysyms.py
```

**Comment by stefanor** [comment]
These are in dist-packages in recent releases, and pymodules in older ones. dpkg doesn't know about anything in pymodules, that stuff is maintained entirely by shell scripts.

**Comment by stefanor** [comment]
Needs to lose some commits and get a merge. Or just be completely revamped.

**Comment by zoidbergwill** [comment]
I'll kill it. It can be revamped when it matters.

**Pull request closed without merging**
